[project]
name = "2025"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "z3-solver>=4.15.4.0",
]

[dependency-groups]
dev = [
    "debugpy>=1.8.17",
    "mypy>=1.19.0",
]

[tool.pyright]
reportAny = false
reportExplicitAny = false
